### PR TITLE
GitLab CI integration

### PR DESCRIPTION
**Pull request by pothitos**
Good afternoon, Stav, and thank you very much for the awesome article!

I created a `.gitlab-ci.yml` file, in case someone wants to run your code in GitLab.

### CODE REVIEW

**Comment by stavshamir** [comment]
Hi, thanks for the suggested contribution! Let me 1up you - since I don't really know GitLab CI, why don't you write a post in the spirit of the post related to this repository, explaining the files you wish to add? I will link it from by blog if you'd like.

**Comment by pothitos** [comment]
Hello, Stav! Yes, this is a good idea! I will try to create a separate tutorial page in Markdown when I have time and come back to this pull request :wink:

**Comment by pothitos** [comment]
Good afternoon, Stav! I just added a _Docker Compose Integration to GitLab CI_ guide in Markdown format. You can read it [rendered](https://gitlab.com/TrendDotFarm/docker-tutorial/blob/master/GitLab-CI.md).

**Comment by stavshamir** [comment]
Great guide, thanks! I'll add a link to it in the original article with credit.

**Comment by pothitos** [comment]
Thank you very much, Stav too! I got a precious lesson from your article and just wanted to give back :wink:

**Pull request merged**
